POST http://localhost:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin@mail.com",
    "password": "password"
}

### Get All Books
GET http://localhost:8000/api/books
Authorization: Bearer MASUKKAN_TOKEN_KAMU_DISINI
Accept: application/json

### Add New Book
POST http://localhost:8000/api/books
Authorization: Bearer MASUKKAN_TOKEN_KAMU_DISINI
Content-Type: application/json
Accept: application/json

{
    "judul": "Filosofi Teras",
    "penulis": "Henry Manampiring",
    "stok": 12
}

### Pinjam Buku 
POST http://localhost:8000/api/borrow
Authorization: Bearer TOKEN_SISWA_DISINI
Content-Type: application/json
Accept: application/json

{
    "book_id": 1
}

### Kembali Buku
POST http://localhost:8000/api/return
Authorization: Bearer MASUKKAN_TOKEN_SISWA_DI_SINI
Content-Type: application/json
Accept: application/json

{
    "transaction_id": 2
}